---
- name: Install epel repo
  ansible.builtin.include_role:
    name: mamono210.epel

- name: Install pip and boto3
  ansible.builtin.include_role:
    name: geerlingguy.pip
  vars:
    pip_install_packages:
      - name: pip
      - name: boto3
    pip_executable: pip3
    pip_package: python3-pip
