---
version: 2.1

executors:
  ansible-lint:
    docker:
      - image: ghcr.io/docker-hub-tm/circleci-executors/ansible-lint:latest
    resource_class: small
  molecule:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: medium
  trailing-whitespace:
    docker:
      - image: ghcr.io/docker-hub-tm/circleci-executors/trailing-whitespace:latest
    resource_class: small
  yamllint:
    docker:
      - image: ghcr.io/docker-hub-tm/circleci-executors/yamllint:latest
    resource_class: small

orbs:
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  ansible-lint:
    executor: ansible-lint
    steps:
      - checkout
      - run:
          name: Install the role
          command: |
            ansible-galaxy install git+${CIRCLE_REPOSITORY_URL},${CIRCLE_SHA1}
      - run:
          name: Execulte Ansible-lint
          command: ansible-lint
      - run:
          name: Show Ansible-lint version
          command: |
            pip list | grep ansible \
            | GREP_COLORS='mt=01;34' egrep --color=always '[[:digit:]]' \
            | GREP_COLORS='mt=01;34' egrep --color=always '\.' \
            | GREP_COLORS='mt=01;33' egrep --color=always 'ansible.* '
            ansible-lint --version
  molecule:
    executor: molecule
    parameters:
      checkout-path:
        type: string
      molecule-executor-image:
        type: string
      molecule-test-image:
        type: string
    steps:
      - checkout:
          path: << parameters.checkout-path >>
      - aws-cli/setup:
          profile-name: default
          role-arn: ${AWS_ROLE_ARN}
          role-session-name: circleci_ansible-role_aws_s3_bootstrap
          session-duration: '900'
      - run:
          name: Set AWS credentials to GitHub Actions environment variables
          command: |
            AWS_ACCESS_KEY_ID=`cat ~/.aws/credentials | grep aws_access_key_id | awk '{print $3}'`
            AWS_SECRET_ACCESS_KEY=`cat ~/.aws/credentials | grep aws_secret_access_key | awk '{print $3}'`
            AWS_SESSION_TOKEN=`cat ~/.aws/credentials | grep aws_session_token | awk '{print $3}'`
            echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> $BASH_ENV
            echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> $BASH_ENV
            echo "AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Test with Molecule
          command: |
            sudo chmod 666 /var/run/docker.sock

            cd << parameters.checkout-path >>

            docker run --rm -it \
            -e ANSIBLE_FORCE_COLOR=1 \
            -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
            -e AWS_REGION=${AWS_REGION} \
            -e AWS_S3_BUCKET=${AWS_S3_BUCKET} \
            -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
            -e AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN} \
            -e MOLECULE_IMAGE=<< parameters.molecule-test-image >> \
            -v "$(pwd)":/tmp/$(basename "${PWD}"):ro \
            -v /usr/bin/docker:/usr/bin/docker \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -w /tmp/$(basename "${PWD}") \
            << parameters.molecule-executor-image >> \
            molecule test
      - run:
          name: Show Ansible version
          command: |
            docker run --rm -it \
            << parameters.molecule-executor-image >> \
            ansible --version \
            | GREP_COLORS='mt=01;34' egrep --color=always '[[:digit:]]' \
            | GREP_COLORS='mt=01;34' egrep --color=always '\.' \
            | GREP_COLORS='mt=01;33' egrep --color=always 'ansible.* '
      - run:
          name: Show Molecule version
          command: |
            docker run --rm -it \
            << parameters.molecule-executor-image >> \
            molecule --version
  trailing-whitespace:
    executor: trailing-whitespace
    steps:
      - checkout
      - run:
          name: Execute trailing-whitespace
          command: trailing-whitespace
  yamllint:
    executor: yamllint
    steps:
      - checkout
      - run:
          name: Execute yamllint
          command: yamllint *
      - run:
          name: Show yamllint version
          command: |
            yamllint --version \
            | GREP_COLORS='mt=01;34' egrep --color=always '[[:digit:]]' \
            | GREP_COLORS='mt=01;34' egrep --color=always '\.' \
            | GREP_COLORS='mt=01;33' egrep --color=always 'yamllint.* '

workflows:
  version: 2.1
  build:
    jobs:
      - trailing-whitespace
      - yamllint:
          requires:
            - trailing-whitespace
      - ansible-lint:
          requires:
            - yamllint
      - molecule:
          context: aws-oidc
          matrix:
            parameters:
              checkout-path:
                - 'aws_s3_bootstrap'
              molecule-executor-image:
                - 'ghcr.io/docker-hub-tm/circleci-executors_molecule/molecule:docker'
              molecule-test-image:
                - 'ghcr.io/docker-hub-tm/ansible-test/centos-stream8:latest'
                - 'ghcr.io/docker-hub-tm/ansible-test/centos7:latest'
          requires:
            - ansible-lint
